name: 'my_dbt_project'
version: '1.0'

profile: 'default'

model-paths: "models"
seed-paths: "data"
analysis-paths: "analysis"
test-paths: "tests"
macro-paths: "macros"
snapshot-paths: "snapshots"

target-path: "target"  # directory which will store ephemeral artifacts
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

config-version: 2

models:
  my_dbt_project: